// Room
export const GET_ROOMS = 'GET_ROOMS';
export const ROOMS_ERROR = 'ROOMS_ERROR';
export const FIND_ROOM = 'FIND_ROOM';
export const GET_ASSETS_ROOM = 'GET_ASSETS_ROOM';
export const GET_ROOMS_LOWER_THAN = 'GET_ROOMS_LOWER_THAN';
export const GET_ROOMS_HIGHER_OR_EQUAL_THAN = ' GET_ROOMS_HIGHER_OR_EQUAL_THAN';
export const SET_CURRENT_ROOM = 'SET_CURRENT_ROOM';
export const CLEAR_CURRENT_ROOM = 'CLEAR_CURRENT_ROOM';

// Asset
export const ASSETS_ERROR = 'ASSETS_ERROR';
export const SET_CURRENT_ASSET = 'SET_CURRENT_ASSET';
export const CLEAR_CURRENT_ASSET = 'CLEAR_CURRENT_ASSET';
export const GET_ASSETS_OF_ROOM = 'GET_ASSETS_OF_ROOM';
export const ADD_TICKET_TO_ASSET = 'ADD_TICKET_TO_ASSET';

// Ticket
export const GET_TICKETS_OF_ASSET = 'GET_TICKETS_OF_ASSET';
export const GET_TICKETS = 'GET_TICKETS';
export const UPVOTE_TICKET = 'UPVOTE_TICKET';
export const TICKETS_ERROR = 'TICKETS_ERROR';
export const DELETE_TICKET = 'DELETE_TICKET';

// Shared
export const SET_LOADING = 'SET_LOADING';
